### ISSUE TITLE
How do I build this for web?

### ISSUE THREAD

**Issue by SmokeSouls** [AgileVisionCompany/Simple-Tourism-VR-with-React-360#2]
Hi, I ran `npm install` and `npm start` and it works just fine locally on port 8081. However, how do I host this on my web server? I cannot find something equivalent to `npm run build`. I am slightly confused as this uses React Native as well. Will I be needing `react-native-web` for this?

**Comment by glibiq** [comment]
Hello, I've updated the package so please pull to get the latest changes.
Please run 
`npm run bundle`
then go to the build directory which will be created after you run the *bundle* command
and run your **web server**, 
I've tested by running 
`npx http-server` and everything worked.

**Comment by SmokeSouls** [comment]
@glibiq Thank you for the changes. Everything works, appreciate it. The only minor problem is that the `static_assets` folder is expected in the `build` folder. Once I copy it there it works as intended.

**Comment by glibiq** [comment]
@SmokeSouls I've added https://github.com/AgileVisionCompany/Simple-Tourism-VR-with-React-360/blob/master/build.sh
build script to automate this.
